name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
        token: ${{secrets.GITHUB_TOKEN}}
    - name: Z88DK Toolchain Setup
      run: |
        sudo snap install z88dk --beta
        sudo apt install cmake ninja-build
    - name: Build
      run: |
        export Z88DK_HOME=/snap/z88dk/current
        export ZCCCFG=${Z88DK_HOME}/share/z88dk/lib/config
        export PATH=${Z88DK_HOME}/bin:${PATH}
        mkdir build
        cd build
        /usr/bin/cmake -DCMAKE_TOOLCHAIN_FILE=../cmake/z88dk.cmake -GNinja ..
        ninja
