name: Release

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
        token: ${{secrets.GITHUB_TOKEN}}
    - name: Z88DK Toolchain Setup
      run: |
        sudo snap install z88dk --beta
        sudo apt install cmake
    - name: Build
      run: |
        export Z88DK_HOME=/snap/z88dk/current
        export ZCCCFG=${Z88DK_HOME}/share/z88dk/lib/config
        export PATH=${Z88DK_HOME}/bin:${PATH}
        mkdir build
        cd build
        cmake ..
        make
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/example.rom"
        token: ${{ secrets.GITHUB_TOKEN }}
